# Generated by Django 3.0.3 on 2020-08-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('football_team', models.CharField(max_length=50)),
            ],
        ),
    ]
