# Generated by Django 3.0.3 on 2020-08-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epl_players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='cur_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
