# Generated by Django 3.0.3 on 2020-09-14 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epl_players', '0002_player_cur_score'),
        ('draft', '0005_auto_20200914_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='player_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_1', to='epl_players.Player'),
        ),
    ]
