# Generated by Django 3.0.3 on 2020-09-15 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('epl_players', '0002_player_cur_score'),
        ('draft', '0008_auto_20200914_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='draft_position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DraftZone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('current_pick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft.League')),
                ('players_chosen', models.ManyToManyField(blank=True, null=True, related_name='players_chosen', to='epl_players.Player')),
            ],
        ),
    ]
