# Generated by Django 3.0.3 on 2020-12-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epl_players', '0002_player_cur_score'),
        ('draft', '0010_auto_20200915_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='player_1',
        ),
        migrations.RemoveField(
            model_name='team',
            name='player_10',
        ),
        migrations.RemoveField(
            model_name='team',
            name='player_11',
        ),
        migrations.RemoveField(
            model_name='team',
            name='player_12',
        ),
        migrations.RemoveField(
            model_name='team',
            name='player_13',
        ),
        migrations.RemoveField(
            model_name='team',
            name='player_14',
        ),
        migrations.RemoveField(
            model_name='team',
            name='player_15',
        ),
        migrations.RemoveField(
            model_name='team',
            name='player_2',
        ),
        migrations.RemoveField(
            model_name='team',
            name='player_3',
        ),
        migrations.RemoveField(
            model_name='team',
            name='player_4',
        ),
        migrations.RemoveField(
            model_name='team',
            name='player_5',
        ),
        migrations.RemoveField(
            model_name='team',
            name='player_6',
        ),
        migrations.RemoveField(
            model_name='team',
            name='player_7',
        ),
        migrations.RemoveField(
            model_name='team',
            name='player_8',
        ),
        migrations.RemoveField(
            model_name='team',
            name='player_9',
        ),
        migrations.AddField(
            model_name='team',
            name='players_chosen',
            field=models.ManyToManyField(blank=True, null=True, related_name='team_players', to='epl_players.Player'),
        ),
    ]
